import { useRouter } from 'next/router';
import { SignInButton, useUser, UserButton } from "@clerk/nextjs"; // Clerk's UserButton for profile dropdown
import Head from "next/head";
import { api } from "~/utils/api";
import Link from "next/link";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import { Card, CardContent } from "~/components/ui/card";
import { HomeIcon, PlusIcon } from '@heroicons/react/24/outline';

export default function Home() {
  const { isSignedIn } = useUser();
  const { data: posts, isLoading } = api.post.getAll.useQuery(); 
  const router = useRouter();

  return (
    <>
      <Head>
        <title>GamePlay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full flex-col bg-background">
        <header className="sticky top-0 z-10 flex h-14 items-center bg-background px-4 shadow-sm">
          <Link href="/" className="mr-4 flex items-center">
            <span className="font-semibold text-lg">GamePlay</span>
          </Link>
          <div className="relative flex-1">
            <Input
              type="search"
              placeholder="Search for games and creators"
              className="w-full rounded-full bg-muted px-8 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary"
            />
          </div>
          <div className="flex items-center gap-4">
            {!isSignedIn ? (
              <SignInButton>
                <Button variant="outline">SIGN IN</Button>
              </SignInButton>
            ) : (
              // Show UserButton with profile and sign-out options
              <UserButton afterSignOutUrl="/" />
            )}
          </div>
        </header>

        <div className="flex flex-1 overflow-auto">
          <nav className="flex flex-col items-start gap-2 border-r bg-background px-4 py-6">
            <Button
              variant="ghost"
              size="sm"
              className="w-full justify-start gap-2 rounded-md px-3 py-2 text-left font-medium hover:bg-muted"
              onClick={() => router.push("/")}
            >
              <HomeIcon className="h-5 w-5" />
              For You
            </Button>
            <Button
              onClick={() => router.push("/create-post")}
              variant="ghost"
              size="sm"
              className="w-full justify-start gap-2 rounded-md px-3 py-2 text-left font-medium hover:bg-muted"
            >
              <PlusIcon className="h-5 w-5" />
              Create
            </Button>
          </nav>

          <div className="flex-1 overflow-auto">
            <div className="relative h-full">
              <Card className="absolute inset-0 h-full w-full overflow-hidden rounded-none">
                <CardContent className="relative h-full">
                  {isLoading ? (
                    <div>Loading posts...</div>
                  ) : (
                    posts?.map((post) => (
                      <div key={post.id} className="mb-4">
                        <img
                          src={post.fileUrl} 
                          alt={post.title}
                          className="h-full w-full object-cover"
                          style={{ aspectRatio: "16/9", objectFit: "cover" }}
                        />
                        <div className="p-4">
                          <h2 className="text-lg font-bold">{post.title}</h2>
                          <p>{post.content || 'No description provided'}</p>
                        </div>
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
