import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";
import Link from "next/link";
import { Input } from "~/components/ui/input";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "~/components/ui/dropdown-menu";
import { Button } from "~/components/ui/button";
import { Card, CardContent } from "~/components/ui/card";
import { BookmarkIcon, HeartIcon, HomeIcon, ChatBubbleOvalLeftIcon, GlobeAltIcon, UserCircleIcon, UsersIcon, MusicalNoteIcon} from '@heroicons/react/24/outline';

export default function Home() {
  const { isSignedIn } = useUser();
  const { data } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>GamePlay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full flex-col bg-background">
        <header className="sticky top-0 z-10 flex h-14 items-center bg-background px-4 shadow-sm">
          <Link href="#" className="mr-4 flex items-center">
            <GlobeAltIcon className="h-6 w-6 mr-2" />
            <span className="font-semibold text-lg">GamePlay</span>
          </Link>
          <div className="relative flex-1">
            <Input
              type="search"
              placeholder="Search for games and creators"
              className="w-full rounded-full bg-muted px-8 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary"
            />
          </div>
          <div className="flex items-center gap-4">
            {!isSignedIn ? (
              <SignInButton>
                <Button variant="outline">SIGN IN</Button>
              </SignInButton>
            ) : (
              <>
                <SignOutButton>
                  <Button variant="outline" size="icon">
                    <UserCircleIcon className="h-6 w-6" />
                  </Button>
                </SignOutButton>
              </>
            )}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
                  <UserCircleIcon className="h-6 w-6" />
                  <span className="sr-only">User Menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>User Menu</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Profile</DropdownMenuItem>
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </header>

        <div className="flex flex-1 overflow-auto">
          <nav className="flex flex-col items-start gap-2 border-r bg-background px-4 py-6">
            <Button
              variant="ghost"
              size="sm"
              className="w-full justify-start gap-2 rounded-md px-3 py-2 text-left font-medium hover:bg-muted"
            >
              <HomeIcon className="h-5 w-5" />
              For You
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="w-full justify-start gap-2 rounded-md px-3 py-2 text-left font-medium hover:bg-muted"
            >
              <UsersIcon className="h-5 w-5" />
              Following
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="w-full justify-start gap-2 rounded-md px-3 py-2 text-left font-medium hover:bg-muted"
            >
              <UserCircleIcon className="h-5 w-5" />
              Profile
            </Button>
            <div className="mt-auto space-y-2 text-sm text-muted-foreground">
              <Link href="#" className="hover:underline">
                Company
              </Link>
              <Link href="#" className="hover:underline">
                Program
              </Link>
              <Link href="#" className="hover:underline">
                Terms & Policies
              </Link>
            </div>
          </nav>

          <div className="flex-1 overflow-auto">
            <div className="relative h-full">
              <Card className="absolute inset-0 h-full w-full overflow-hidden rounded-none">
                <CardContent className="relative h-full">
                  {data?.map((post: { id: number; content: string }) => (
                    <div key={post.id}>
                      <img
                        src="/placeholder.svg"
                        alt="Game Thumbnail"
                        width={800}
                        height={800}
                        className="h-full w-full object-cover"
                        style={{ aspectRatio: "800/800", objectFit: "cover" }}
                      />
                      <div className="absolute bottom-0 left-0 w-full bg-gradient-to-t from-black/80 to-transparent p-4 text-white">
                        <div className="flex items-center justify-between">
                          <div className="space-y-1">
                            <div className="text-sm font-medium">{post.content}</div>
                            <div className="text-xs text-muted-foreground">Shooter Game</div>
                          </div>
                          <div className="flex items-center gap-2">
                            <Button variant="ghost" size="icon" className="rounded-full p-1 hover:bg-white/20">
                              <HeartIcon className="h-5 w-5" />
                            </Button>
                            <Button variant="ghost" size="icon" className="rounded-full p-1 hover:bg-white/20">
                              <ChatBubbleOvalLeftIcon className="h-5 w-5" />
                            </Button>
                            <Button variant="ghost" size="icon" className="rounded-full p-1 hover:bg-white/20">
                              <BookmarkIcon className="h-5 w-5" />
                            </Button>
                            <Button variant="ghost" size="icon" className="rounded-full p-1 hover:bg-white/20">
                              <Share2Icon className="h-5 w-5" />
                            </Button>
                          </div>
                        </div>
                        <div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground">
                          <MusicalNoteIcon className="h-4 w-4" />
                          AcShooter Soundtrack
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function Share2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" x2="15.42" y1="13.51" y2="17.49" />
      <line x1="15.41" x2="8.59" y1="6.51" y2="10.49" />
    </svg>
  );
}